name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.mramirahmadi }}" | docker login -u "${{ secrets.mramirahmadi }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t username/hello-world-nodejs:latest .


    - name: Push Docker Image
      run: docker push mramirahmadi/hello-world-nodejs:latest


    - name: Run tests
      run: docker run -d -p 3000:3000 mramirahmadi/hello-world-nodejs:latest && curl http://localhost:3000
